packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalog:
  '@antfu/eslint-config': ^5.4.1
  '@antfu/ni': ^26.0.1
  '@antfu/utils': ^9.2.1
  '@eslint/compat': ^1.4.0
  '@preact/signals-react': ^3.3.0
  '@types/fs-extra': ^11.0.4
  '@types/node': ^24.5.2
  '@types/react': ^19.1.15
  '@types/react-dom': ^19.1.9
  '@vitejs/plugin-react': ^5.0.4
  bumpp: ^10.2.3
  eslint: ^9.36.0
  eslint-plugin-react-hooks: ^7.0.0
  esno: ^4.8.0
  fs-extra: ^11.3.2
  globals: ^16.4.0
  lint-staged: ^16.2.3
  react: ^19.1.1
  react-cosmos: ^7.0.0
  react-cosmos-plugin-vite: ^7.0.0
  react-dom: ^19.1.1
  simple-git-hooks: ^2.13.1
  tsup: ^8.5.0
  typescript: ^5.9.2
  vite: ^7.1.7
  vitest: ^3.2.4

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
