packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalog:
  '@antfu/eslint-config': ^6.1.0
  '@antfu/ni': ^27.0.1
  '@antfu/utils': ^9.3.0
  '@eslint/compat': ^1.4.0
  '@preact/signals-react': ^3.3.1
  '@types/fs-extra': ^11.0.4
  '@types/node': ^24.9.1
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@vitejs/plugin-react': ^5.1.0
  bumpp: ^10.3.1
  eslint: ^9.38.0
  eslint-plugin-react-hooks: ^7.0.1
  esno: ^4.8.0
  fs-extra: ^11.3.2
  globals: ^16.4.0
  lint-staged: ^16.2.6
  react: ^19.2.0
  react-cosmos: ^7.0.0
  react-cosmos-plugin-vite: ^7.0.0
  react-dom: ^19.2.0
  simple-git-hooks: ^2.13.1
  tsup: ^8.5.0
  typescript: ^5.9.3
  vite: ^7.1.12
  vitest: ^4.0.4

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
